CREATE TABLE IF NOT EXISTS customers
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name CHARACTER VARYING(320) NOT NULL,
    phone CHARACTER VARYING(32) NOT NULL,
    email CHARACTER VARYING(320) NOT NULL,
    address CHARACTER VARYING(255) NOT NULL,
    city CHARACTER VARYING(255) NOT NULL,
    postal_code CHARACTER VARYING(12) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
)